# Generated by Django 4.0.6 on 2022-07-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rashik', '0002_alter_image_bold_alter_image_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='bold',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='image',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
